Introduction

Convolutional Neural Networks (CNNs) are a specialized type of neural network designed for image processing tasks. Images contain a large number of pixels, and treating each pixel as an independent feature leads to an enormous number of parameters. CNNs solve this problem by learning local patterns through convolution operations. Instead of focusing on individual pixels, they examine groups of neighboring pixels and learn meaningful visual features such as edges, curves, textures and shapes. These extracted features are then used for image classification and other computer vision tasks.

Why Traditional Neural Networks Struggle with Images

A traditional neural network requires every pixel to be connected to neurons in the next layer. For a small image this may be manageable, but as image size increases, the number of weights grows rapidly. For example, a 100 × 100 image contains 10,000 pixels. Connecting all these pixels to even a modest hidden layer would require an extremely large number of parameters. This increases memory usage, training time and the risk of overfitting. Furthermore, standard neural networks do not naturally capture spatial relationships between neighboring pixels.

Convolution Operation

The core operation in a CNN is convolution. A small matrix called a filter or kernel is moved across the image. At each position, the filter values are multiplied with the corresponding pixel values and then summed together. This produces a single value that represents how strongly that filter matches that region of the image. Repeating this process across the entire image generates a feature map.

In [1]:
import numpy as np

image = np.array([
    [1,1,0,0],
    [1,1,0,0],
    [0,0,1,1],
    [0,0,1,1]
])

kernel = np.array([
    [1,0],
    [0,1]
])

output = []

for i in range(3):
    row = []
    for j in range(3):
        region = image[i:i+2, j:j+2]
        row.append(np.sum(region * kernel))
    output.append(row)

print(np.array(output))

[[2 1 0]
 [1 2 1]
 [0 1 2]]


Feature Maps

The result of applying a filter to an image is called a feature map. A feature map highlights locations where a particular pattern is detected. Different filters learn different features. Some may detect horizontal edges, while others may identify vertical edges, corners or textures. As training progresses, the network automatically learns which features are most useful for classification.

ReLU Activation Function

After convolution, the feature map is usually passed through an activation function called ReLU (Rectified Linear Unit). ReLU replaces negative values with zero while keeping positive values unchanged. This introduces non-linearity into the network and helps the model learn more complex patterns.

In [2]:
import numpy as np

feature_map = np.array([
    [-2, 3, -1],
    [4, -5, 6]
])

relu_output = np.maximum(0, feature_map)

print(relu_output)

[[0 3 0]
 [4 0 6]]


Pooling

Pooling is used to reduce the size of feature maps while retaining important information. By reducing dimensions, pooling decreases computational requirements and helps prevent overfitting. The most common pooling technique is max pooling, where the largest value from a region is selected.

In [3]:
feature_map = np.array([
    [1,4],
    [2,3]
])

print(np.max(feature_map))

4


Fully Connected Layer

After several rounds of convolution, activation and pooling, the resulting feature maps are flattened into a one-dimensional vector. This vector is then passed to a fully connected neural network. The fully connected layer combines all extracted features and produces the final classification output. For example, in an image classification task, the output layer may predict whether the image contains a cat, dog or bird.

Complete CNN Workflow

A convolutional neural network processes an image through multiple stages. First, convolution filters extract useful features from the image. These features are then passed through activation functions to introduce non-linearity. Pooling layers reduce dimensionality and retain important information. Finally, the processed features are flattened and sent to fully connected layers that generate the final prediction.

Advantages of CNNs

CNNs dramatically reduce the number of parameters compared to traditional neural networks and are capable of learning complex visual features automatically. They take advantage of spatial relationships between pixels and are robust to small shifts in object position. Because of these properties, CNNs have become the standard architecture for image-related machine learning tasks.