In [16]:
import numpy as np

marks = np.array([85,90,78,92])

print(marks)


[85 90 78 92]


BASICS

In [5]:
print(marks.ndim)
print(marks.shape)
print(marks.dtype)
print(marks.itemsize)
print(marks.nbytes)
print(marks.size)

1
(4,)
int64
8
32
4


Indexing and Slicing

In [6]:
attendance = np.array([
    [92,95,88,90],
    [85,87,89,91]
])

attendance[0]
attendance[:,2]
attendance[1,3]
attendance[0,1:4:2]

array([95, 90])

3D Arrays

In [7]:
lab_scores = np.array([
    [[12,15],[18,20]],
    [[25,30],[35,40]]
])

print(lab_scores)

lab_scores[0,1,1]

lab_scores[:,1,:]

[[[12 15]
  [18 20]]

 [[25 30]
  [35 40]]]


array([[18, 20],
       [35, 40]])

Array Initialization

In [8]:
np.zeros((3,4))

np.ones((2,3))

np.full((3,3),7)

np.identity(4)

np.random.rand(4,4)

np.random.randint(1,100,size=(5,5))

np.repeat([[1,2]],4,axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

Pattern Problem

In [9]:
pattern = np.ones((7,7))

inner = np.zeros((5,5))

inner[2,2] = 9

pattern[1:-1,1:-1] = inner

print(pattern)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 9. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Copying Arrays

In [10]:
a = np.array([10,20,30])

b = a.copy()

b[0] = 100

print(a)
print(b)

[10 20 30]
[100  20  30]


Mathematics

In [11]:
a = np.array([2,4,6,8])

a + 3

a - 1

a * 2

a / 2

a ** 2

np.sin(a)

np.cos(a)

np.tan(a)

array([-2.18503986,  1.15782128, -0.29100619, -6.79971146])

Linear Algebra

In [12]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

np.matmul(A,B)

np.linalg.det(A)

np.trace(A)

np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Statistics

In [13]:
scores = np.array([
    [80,90,85],
    [75,95,88]
])

np.min(scores)

np.max(scores)

np.mean(scores)

np.sum(scores)

np.std(scores)

np.float64(6.551081335677848)

Reshape

In [14]:
arr = np.arange(12)

arr.reshape(3,4)

arr.reshape(2,6)

arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Stack

In [15]:
a = np.array([1,2,3])

b = np.array([4,5,6])

np.vstack((a,b))

np.hstack((a.reshape(3,1),
           b.reshape(3,1)))

array([[1, 4],
       [2, 5],
       [3, 6]])

File Loading


In [ ]:
data = np.genfromtxt(
    "../datasets/student_scores.txt",
    delimiter=","
)

print(data)

Boolean Masking

In [ ]:
data > 50

data[data > 50]

data[(data > 20) & (data < 80)]

data[data % 2 == 0]